name: viserpay
description: A new Flutter project.

publish_to: 'none'
version: 1.2.7+12

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI / animations
  toastification: ^3.0.3
  flutter_advanced_switch: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.17.1
  lottie: ^3.1.2
  octo_image: ^2.0.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  carousel_slider: ^5.0.0
  circular_countdown_timer: ^0.2.3
  flutter_animate: ^4.5.0
  zoom_tap_animation: ^1.1.0
  dots_indicator: ^4.0.1
  dotted_border: ^3.1.0
  expandable_page_view: ^1.0.17
  another_flushbar: ^1.12.30

  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^19.5.0

  flutter_inappwebview: ^6.0.0
  table_calendar: ^3.0.9

  # Gestion d’état et utilitaires
  get: ^4.6.6
  http: ^1.1.2
  dio: ^5.4.3+1
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2
  flutter_exit_app: ^2.0.0
  restart_app: ^1.2.1
  local_auth: ^3.0.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1

  # QR / Code / fichiers
  image_picker: ^1.2.1
  file_picker: ^10.3.2
  file_manager: ^1.0.2
  open_file: ^3.3.2
  pdf: ^3.10.2
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  share_plus: ^12.0.1
  fast_contacts: ^5.0.1
  flutter_phone_direct_caller: ^2.2.1

  # Internationalisation
  intl: ^0.20.2

  # Fonts / icônes
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/app_logo_white.png
    - assets/icon/
    - assets/img/
    - assets/animation/

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-Light.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
